name: 'Green-Box-Count'
description: 'Generate a SVG displaying your contribution streak'
inputs:
  github-token:
    description: 'GitHub Secret Token'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'